### ISSUE TITLE
Window transparency on 0.0.3

### ISSUE THREAD

**Issue by cmdrflexo** [the-expanse/OpenStoreVR#5]
![image](https://user-images.githubusercontent.com/4148613/58212920-6adcda80-7cbe-11e9-8306-e8b9c983dd05.png)

**Comment by shaneharris** [comment]
ill try to recreate, cheers!

**Comment by cmdrflexo** [comment]
i just noticed the white corner bit shows up when you open the debugger and doesn't go away unless you restart the program

**Comment by shaneharris** [comment]
ah ok, this might not be fixable then in that case, its a quirk of electron.

close for now!
