### ISSUE TITLE
stuck at loading apps...

### ISSUE THREAD

**Issue by elhenro** [the-expanse/OpenStoreVR#8]
I used the windows version,
did the setup steps and i can open the launcher on the quest,
but on my desktop app no apps, experiences or games are loading.

**Comment by soukron** [comment]
Same here. Installed launcher but it fails when:
 - loading apps, experiences or games
 - sideload the Expanse

**Comment by shaneharris** [comment]
Hi Guys, 

I have released a new version 0.0.3 which was a breaking verison ( changed how the apps loaded in completely - now using fdroid repos so it works like repos on kodi ). Ive also added drag and drop support for installing arbitrary APK files.

You can get the new version here - https://github.com/the-expanse/OpenStoreVR/releases/tag/0.0.3

I have also updated the reddit posts. 

Sorry for the hassle!

**Comment by elhenro** [comment]
ah cool, thanks for the quick and honest answer.
good idea with the debugger! imo it was lacking verbosity, too
will try again now :)
