### ISSUE TITLE
Refresh keeps on cycling every few seconds by itself

### ISSUE THREAD

**Issue by hollmrl** [the-expanse/OpenStoreVR#9]
After 0.0.3 loads everything, the program keeps refreshing itself every few seconds by itself.  Makes it very difficult to do anything since the program goes back to the home screen after each refresh.

**Comment by shaneharris** [comment]
fixed in the latest version - i have replaces the 0.0.3 release so its the same release download . Sorry about that it im sure it was frustrating!

**Comment by hollmrl** [comment]
Thanks for the quick fix.
